import {
  Investigation,
  UserProfile,
  ConnectedProvider,
  UsageMetrics,
} from '../types';

export const mockUserProfile: UserProfile = {
  id: 'usr_mech_8892',
  name: 'Vedant Sharma',
  email: 'vedant@mechamaru.ai',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  role: 'Tech Lead',
  githubHandle: 'Vedanto28',
  joinedAt: '2026-01-15',
  twoFactorEnabled: true,
};

export const mockConnectedProviders: ConnectedProvider[] = [
  {
    id: 'prov_github_01',
    providerId: 'github',
    name: 'GitHub MCP Server',
    status: 'connected',
    lastUsedAt: '2 mins ago',
    isByok: false,
    maskedKey: 'ghp_****99999',
    quotaUsed: 1420,
  },
  {
    id: 'prov_openai_02',
    providerId: 'openai',
    name: 'OpenAI GPT-4o / O1',
    status: 'connected',
    lastUsedAt: '1 hour ago',
    isByok: true,
    maskedKey: 'sk-proj-****4921',
    quotaUsed: 89000,
  },
  {
    id: 'prov_gemini_03',
    providerId: 'gemini',
    name: 'Google Gemini 1.5 Pro',
    status: 'connected',
    lastUsedAt: 'Just now',
    isByok: false,
    maskedKey: 'AIzaSy****8821',
    quotaUsed: 31000,
  },
  {
    id: 'prov_anthropic_04',
    providerId: 'anthropic',
    name: 'Anthropic Claude 3.5 Sonnet',
    status: 'disconnected',
    lastUsedAt: '3 days ago',
    isByok: true,
    maskedKey: 'sk-ant-****1102',
  },
  {
    id: 'prov_groq_05',
    providerId: 'groq',
    name: 'Groq Llama-3-70B',
    status: 'connected',
    lastUsedAt: '4 hours ago',
    isByok: true,
    maskedKey: 'gsk_****7721',
    quotaUsed: 15400,
  },
];

export const mockUsageMetrics: UsageMetrics = {
  currentTier: 'Developer Pro',
  investigationsThisMonth: 148,
  monthlyQuota: 500,
  tokensConsumed: 1420500,
  tokenQuota: 5000000,
  activeSessionsCount: 3,
  mcpCallsCount: 892,
  renewsAt: '2026-08-15',
};

export const mockInvestigations: Investigation[] = [
  {
    id: 'CASE-2941-API-TIMEOUT',
    title: 'Spordic 504 Gateway Timeouts in PaymentGatewayClient',
    status: 'completed',
    mode: 'log_investigation',
    confidenceScore: 85,
    pinned: true,
    archived: false,
    tags: ['Redis', 'Next.js', 'PoolExhaustion', 'Production'],
    createdAt: '2026-07-28 16:55:00',
    updatedAt: '2026-07-28 16:58:20',
    provider: 'OpenAI (BYOK)',
    messageCount: 8,
    steps: [
      {
        id: 'st_1',
        stage: 'Planning',
        status: 'completed',
        label: 'Understanding incident scope',
        durationMs: 400,
        details: 'Parsed 504 logs from Datadog APM stack trace.',
      },
      {
        id: 'st_2',
        stage: 'Repository Inspection',
        status: 'completed',
        label: 'Connecting to GitHub repo & checking pool config',
        durationMs: 1200,
        details: 'Found redis connection pool maxClients set to 50 in backend/server.js.',
      },
      {
        id: 'st_3',
        stage: 'Documentation Search',
        status: 'completed',
        label: 'Searching Context7 for ioredis pool exhaustion options',
        durationMs: 1800,
        details: 'Retrieved pool size recommendations for burst workloads > 100 req/sec.',
      },
      {
        id: 'st_4',
        stage: 'Runtime Analysis',
        status: 'completed',
        label: 'Analyzing runtime metrics',
        durationMs: 2300,
        details: 'Verified queue length spikes during peak traffic bursts.',
      },
      {
        id: 'st_5',
        stage: 'Evidence Synthesis',
        status: 'completed',
        label: 'Generating diagnostic report',
        durationMs: 2900,
        details: 'Report compiled with High confidence.',
      },
    ],
    evidence: [
      {
        id: 'ev_1',
        type: 'code',
        title: 'PaymentGatewayClient Redis Init',
        source: 'backend/src/services/payment.ts',
        lineRange: 'L142-L158',
        snippet: 'const redis = new Redis({ host: process.env.REDIS_HOST, maxClients: 50, enableReadyCheck: false });',
        timestamp: '2026-07-28 16:56:10',
      },
      {
        id: 'ev_2',
        type: 'log',
        title: 'Datadog Trace ERR_REDIS_MAX_CLIENTS',
        source: 'datadog_trace_id:9a3b7c',
        snippet: 'Wait time: 29.8s -> Gateway Timeout 504 on POST /api/v2/checkout/process',
        timestamp: '2026-07-28 16:56:45',
      },
    ],
    report: {
      hypothesis:
        'The 504 timeouts are caused by Redis connection pool exhaustion within the `PaymentGatewayClient`, not the primary Postgres database.',
      confidence: 85,
      evidenceSummary: [],
      assessment:
        'During peak load, concurrent requests to `/api/v2/checkout/process` spawn individual Redis connections to check idempotency keys. The pool size is hardcoded to 50, which is insufficient for bursts over 100 req/sec, leading to queued connections that eventually hit the 30s gateway timeout.',
      nextSteps: [
        "Increase 'REDIS_POOL_SIZE' env var to '200' in production.",
        "Implement connection pooling reuse in 'PaymentGatewayClient' constructor.",
      ],
    },
  },
  {
    id: 'CASE-2940-AUTH-ERR',
    title: 'AUTH-ERR-REDIS-LEAK: Token Revocation Cache Misses',
    status: 'completed',
    mode: 'change_investigation',
    confidenceScore: 92,
    pinned: true,
    archived: false,
    tags: ['Auth', 'JWT', 'Security', 'GitDiff'],
    createdAt: '2026-07-27 11:20:00',
    updatedAt: '2026-07-27 11:24:15',
    provider: 'Gemini 1.5 Pro',
    messageCount: 5,
    steps: [],
    evidence: [],
  },
  {
    id: 'CASE-2938-DB-LATENCY',
    title: 'Postgres Connection Leak in Background Worker Queue',
    status: 'active',
    mode: 'knowledge_debugging',
    confidenceScore: 78,
    pinned: false,
    archived: false,
    tags: ['Postgres', 'BullMQ', 'Worker'],
    createdAt: '2026-07-26 09:12:00',
    updatedAt: '2026-07-26 09:15:00',
    provider: 'OpenAI (BYOK)',
    messageCount: 3,
    steps: [],
    evidence: [],
  },
  {
    id: 'CASE-2932-SSE-LOOP',
    title: 'MCP Transport SSE Reconnect Loop Debugging',
    status: 'completed',
    mode: 'repository_investigation',
    confidenceScore: 98,
    pinned: false,
    archived: false,
    tags: ['MCP', 'SSE', 'CircuitBreaker'],
    createdAt: '2026-07-20 14:00:00',
    updatedAt: '2026-07-20 14:10:00',
    provider: 'Internal MCP',
    messageCount: 12,
    steps: [],
    evidence: [],
  },
  {
    id: 'CASE-2910-CORS-HEADERS',
    title: 'CORS Preflight Failures on Staging Domain API',
    status: 'archived',
    mode: 'normal_chat',
    confidenceScore: 60,
    pinned: false,
    archived: true,
    tags: ['CORS', 'Express', 'Staging'],
    createdAt: '2026-07-15 18:30:00',
    updatedAt: '2026-07-15 18:35:00',
    provider: 'Groq Llama-3',
    messageCount: 2,
    steps: [],
    evidence: [],
  },
];
